### PR TITLE
Missing long description parameter in setup.py

### PR DESCRIPTION
**Pull request by chinmaychahar**
## What does this PR do?

The https://pypi.org/project/appwrite/ fails to load the README.md content as there was no long description parameter for reading the file previously. 
## Test Plan

I read through documentation and need help verifying these changes on the actual project description page.

## Related PRs and Issues

Related to issue [#4304](https://github.com/appwrite/appwrite/issues/4304)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by stnguyen90** [comment]
@chinmayayy, please make sure to make the change in our [sdk-generator](https://github.com/appwrite/sdk-generator) repo.

**Comment by chinmayayy** [comment]
@stnguyen90 could you guide me a bit regarding that? Will https://github.com/chinmayayy/appwrite-sdk-generator/blob/master/src/SDK/Language/Python.php be the targeted file for it?

**Comment by chinmayayy** [comment]
@stnguyen90 I need help understanding if this was the target file in SDK Generator repo that you were mentioning

**Comment by stnguyen90** [comment]
Closing this PR since this repo is read only.

**Pull request closed without merging**
