### PR TITLE
Delete __init__.py

### PR DESCRIPTION
**Pull request by Pranav108**

### CODE REVIEW

**Review by king-11 — COMMENTED** [review]
:-1: seems like spam pr to me

**Comment by eldadfux** [comment]
We love contribution, but we suggest you try and submit more meaningful PRs by exploring any of our [open issues](https://github.com/appwrite/appwrite/issues). If you have any problem or need help, please join our Discord community: https://appwrite.io/discord and use the #maintainers channel.

**Comment by Pranav108** [comment]
> We love contribution, but we suggest you try and submit more meaningful PRs by exploring any of our [open issues](https://github.com/appwrite/appwrite/issues). If you have any problem or need help, please join our Discord community: https://appwrite.io/discord and use the #maintainers channel.

Okay, today is my fist day on git hub ,that's why i might have done several errors .This PR is one among them,. Sorry for your inconvenience.

**Comment by Pranav108** [comment]
> 👎 seems like spam pr to me
Yeah , that might me a spam , but my intention was not to do so. The file was empty that's why i deleted it.

**Comment by king-11** [comment]
__init__.py is used to specify that the folder as a package which then allows internal package imports it can be empty still it works.

**Pull request closed without merging**
