### PR TITLE
Fixing setup.py

### PR DESCRIPTION
**Pull request by PedroCisnerosSantana**
Fixing invalid classifiers and imported libs

### CODE REVIEW

**Comment by eldadfux** [comment]
Hey Pedro, Thanks for helping out!!

This SDK is actually auto-generated from our [SDK-Generator](https://github.com/appwrite/sdk-generator) project. Can you please update this changes in this template: https://github.com/appwrite/sdk-generator/blob/master/templates/python/setup.py.twig and then send a PR?

Also, please note that the license used seems to be OK:
https://opensource.org/licenses/BSD-3-Clause

**Comment by PedroCisnerosSantana** [comment]
Hello @eldadfux I know the license should be OK, but if you take a look in the [https://pypi.org/classifiers/](pypi classifiers) you will see that the only option available is "License :: OSI Approved :: BSD License" that's why I changed it, if we keep the old one we cannot add it to the pypi index. I'm waiting for your response. 
Kind regards.

**Comment by eldadfux** [comment]
OK, got it now! Well than I guess we will have to change the license value specifically for the python generator script.

I guess we should overwrite this line:
https://github.com/appwrite/appwrite/blob/master/app/tasks/sdks.php#L177

In this position:
https://github.com/appwrite/appwrite/blob/master/app/tasks/sdks.php#L149

and also change the order of the script to make it possible.

**Comment by eldadfux** [comment]
@PedroCisnerosSantana I can work on the license fix in Appwrite core repo later today, unless you want to give it a try. Let me know.

**Comment by PedroCisnerosSantana** [comment]
Perfect, I will close this PR and start to work on it, also I will open an issue in the correct repo with information in order to start with it. Thanks

**Pull request closed without merging**
